### ISSUE TITLE
Does not work on scroll on mobile

### ISSUE THREAD

**Issue by mehrdad-shokri** [subtirelumihail/react-fullpage#12]
I have tested this on chrome android and safari ios,  
scrolling does not change slides.  
``react-fullpage``: ``0.1.16``,
``react version``: ``15.4.1``

**Comment by mihailmetro** [comment]
I will test this and try to come up with a fix

**Comment by mehrdad-shokri** [comment]
would somebody answer please?

**Comment by subtirelumihail** [comment]
Can you please copy/paste your console or what kind of error does it gives you ?
