### ISSUE TITLE
Problem at server-side rendering

### ISSUE THREAD

**Issue by flockonus** [subtirelumihail/react-fullpage#15]
Having some issues when rendering on server side, i believe at those lines 
https://github.com/subtirelumihail/react-fullpage/blob/master/src/Section.js#L8
https://github.com/subtirelumihail/react-fullpage/blob/master/src/SectionsContainer.js#L13

Maybe it could be moved inside componentDidMount ?

**Comment by subtirelumihail** [comment]
Can you do a PR so I can look into it ?

**Comment by subtirelumihail** [comment]
This should be fixed
