### ISSUE TITLE
Overscrolling with mac touchpad

### ISSUE THREAD

**Issue by nickpolet** [subtirelumihail/react-fullpage#21]
When using react-fullpage on a mac laptop, using the touchpad, there is an issue that causes it to scroll too far and you end up scrolling two sections when you meant to scroll one.

There is a similar issue on fullpage.js [here](https://github.com/alvarotrigo/fullPage.js/issues/5) and it seems to be somewhat eliminated by using the css3 property. I'm not sure exactly what this does but it seems to fix the issue and they use it one all of their examples (which work well using mac touchpad)

**Comment by lightninglu10** [comment]
is this fixed? I'm still having this issue.
