### ISSUE TITLE
Incompatibility with lightbox integration

### ISSUE THREAD

**Issue by MajorasJack** [subtirelumihail/react-fullpage#26]
My website is utilising a popup Lightbox image gallery, however once the lightbox is closed, the scrolling for fullpage seems to break, for example, having the scrollbar set to false, it seems to forcibly override and add it back.

For reference:
![screenshot from 2017-04-10 10-54-14](https://cloud.githubusercontent.com/assets/6554421/24856301/1e0f5a2c-1ddc-11e7-8e40-a28f3cfe0955.png)

**Comment by subtirelumihail** [comment]
This wasn't meant to support jquery or jquery related plugins, only React components

**Comment by subtirelumihail** [comment]
You can try to use this instead https://github.com/jossmac/react-images/blob/master/README.md
