### ISSUE TITLE
Revert to normal scroll when switching routes.

### ISSUE THREAD

**Issue by 0xpatrickdev** [subtirelumihail/react-fullpage#27]
I have a simple landing page that uses `react-router `, and I'm having issues when navigating away from Fullpage.js.

My render method looks like this, and `react-fullpage` is only active in the Fullpage component:
```javascript
render(
  <Router history={browserHistory}>
    <Route path="/" component={App}>
      <IndexRoute component={Fullpage}/>
      <Route path="/terms" component={Terms}/>
      <Route path="*" component={Fullpage}/>
    </Route>
  </Router>,
  document.getElementById('root')
);
```

When I have `scrollBar: false`, the `Terms` component loads when I navigate to `/terms` but the page scroll is disabled.  When I have `scrollBar: true`, I am able to scroll on the `/terms` route but it initially loads with the same scroll position that the Fullpage route had.

Is there any way to fix this? Either on my end or with a PR to the project? Has anyone else experienced something like this?

**Comment by subtirelumihail** [comment]
Can you submit a PR if you managed to fix this?

**Comment by 0xpatrickdev** [comment]
I wasn't able to fix this @subtirelumihail. I can help if you point me in the right direction.

**Comment by lightninglu10** [comment]
@pcooney10 if you're using react-router you can create a scrollToTop container wrapping the router.

**Comment by 0xpatrickdev** [comment]
Thanks @lightninglu10 ! That did the trick.

If anyone else encounters the same issue, this link was helpful: https://reacttraining.com/react-router/web/guides/scroll-restoration.

And this is the code I used: 
````javascript
import React, {Component} from 'react'

// the wrapper component
class ScrollToTopOnMount extends Component {
  componentDidMount(prevProps) {
    window.scrollTo(0, 0)
  }
  render() {
    return null
  }
}

// the actual component    
export const Terms () => (
  <div>
    <ScrollToTopOnMount/>
    <section>
     /*  .... stuff in my second route outside of react-fullpage ... */
    </section>
  </div>
)
````

**Comment by lightninglu10** [comment]
@pcooney10 is this actually fixed for you?

I'm having issues of switching from a route that's FullPage with scrollBar: false, but then it stays false if I use a <Link> component. How did you fix this?

**Comment by lightninglu10** [comment]
@subtirelumihail is this actually fixed? It doesn't work for me.

When I switch routes from a page that was fullpaged to one that's not, my scrolling is still disabled. This is with scrollbar: false.

**Comment by 0xpatrickdev** [comment]
@lightninglu10 it should be, @subtirelumihail merged the pull request yesterday. I think he still needs to update npm though, I see the package version is stale @ 0.1.16.

**Comment by 0xpatrickdev** [comment]
@lightninglu10 if you need a quick turnaround, you can take my edits in 93e31aa and paste them into your local `node_modules` folder. The edits I made are in `/src`, and your application will reference the compiled files in `/dist`.

**Comment by lightninglu10** [comment]
@pcooney10 cool, yeah I just updated my own app to bring scrolling back after looking through the source code.

**Comment by subtirelumihail** [comment]
Hey, I will update the npm version tonight to 0.1.18, sorry for the delay :(

**Comment by subtirelumihail** [comment]
It's done
