### ISSUE TITLE
server-side rendering

### ISSUE THREAD

**Issue by penguin3069** [subtirelumihail/react-fullpage#4]
There will be an error--'window is not defined' when I use server-side rendering.

**Comment by penguin3069** [comment]
I remove the `windowHeight` property in `getInitialState` method,and add `windowHeight` in `componentDidMount` by `this.setState`.It seems to work.

**Comment by JerryAWalker** [comment]
on the server put this in there..

if (typeof(window) === 'undefined') {
            global.window = {};
}

**Comment by penguin3069** [comment]
Thanks a lot :+1:
