### ISSUE TITLE
arrowNavigation breaks input fields

### ISSUE THREAD

**Issue by Xilver** [subtirelumihail/react-fullpage#50]
When setting arrowNavigation to true, you can no longer navigate in text input fields using arrow keys, and more importantly, you can not type spaces.

This is the offending code in SectionsContainer:
`if([32, 37, 38, 39, 40].indexOf(e.keyCode) > -1) {
    e.preventDefault(); // Prevent unwanted scrolling on Firefox
}`

**Comment by Imagixel** [comment]
same issue here

**Comment by m-muhsin** [comment]
This is fixed
