### ISSUE TITLE
Uncaught Invariant Violation

### ISSUE THREAD

**Issue by dylanfpaul** [subtirelumihail/react-fullpage#9]
Uncaught Invariant Violation: traverseParentPath(...): Cannot traverse from and to the same ID, ``.

Keep getting this error. Seems like it has something to do with the components that SectionsContainer or Section creates.

**Comment by noncototient** [comment]
@dylanfpaul have you managed to figure it out?

**Comment by dylanfpaul** [comment]
I have not my friend!

**Comment by dylanfpaul** [comment]
@noncototient  I have not my friend!

**Comment by njj** [comment]
It has something to do w/ the most recent version of React (or React DOM).  If you use the same version as in this project's package.json the error goes away.

**Comment by fortunto2** [comment]
hi, i have same error
`Uncaught Invariant Violation: traverseParentPath(...): Cannot traverse from and to the same ID`
but i need using with    "react": "15"
what needed change?
thanks

**Comment by lookeme** [comment]
Hello, guys! Have you found any solutions for this issue? I got the same.

**Comment by Rulox** [comment]
Same here, it's a shame :(

**Comment by xpluscal** [comment]
+!

**Comment by xpluscal** [comment]
In case you run into this issue again:

I forked the repo and used the src Classes for Section and SectionsContainer. Worked like a charm.

**Comment by jenyckee** [comment]
+1

**Comment by subtirelumihail** [comment]
This should be fixed in 0.1.16 so closing for the moment
